export const TMDB_API_KEY: Readonly<string> = import.meta.env.TMDB_API_KEY;
export const TMDB_BASE_COVER_IMAGE_URL = `${import.meta.env.VITE_PUBLIC_TMDB_IMAGE_BASE_URL}/original`;
export const TMDB_BASE_COVER_500_IMAGE_URL = `${import.meta.env.VITE_PUBLIC_TMDB_IMAGE_BASE_URL}/w500`;
export const TMDB_BASE_COVER_780_IMAGE_URL = `${import.meta.env.VITE_PUBLIC_TMDB_IMAGE_BASE_URL}/w780`;
export const TMDB_BASE_COVER_1280_IMAGE_URL = `${import.meta.env.VITE_PUBLIC_TMDB_IMAGE_BASE_URL}/w1280`;

export const API_URL_WITH_PROXY = `${import.meta.env.VITE_PUBLIC_CORS_PROXY_BASE_URL}${import.meta.env.VITE_PUBLIC_TMDB_API_BASE_URL}`;
export const TMDB_BASE_COVER_IMAGE_URL_WITH_PROXY = `${import.meta.env.VITE_PUBLIC_CORS_PROXY_BASE_URL}${TMDB_BASE_COVER_IMAGE_URL}`;
export const TMDB_BASE_COVER_500_IMAGE_URL_WITH_PROXY = `${import.meta.env.VITE_PUBLIC_CORS_PROXY_BASE_URL}${TMDB_BASE_COVER_500_IMAGE_URL}`;
export const TMDB_BASE_COVER_780_IMAGE_URL_WITH_PROXY = `${import.meta.env.VITE_PUBLIC_CORS_PROXY_BASE_URL}${TMDB_BASE_COVER_780_IMAGE_URL}`;
export const TMDB_BASE_COVER_1280_IMAGE_URL_WITH_PROXY = `${import.meta.env.VITE_PUBLIC_CORS_PROXY_BASE_URL}${TMDB_BASE_COVER_1280_IMAGE_URL}`;
