name: Build and Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.9.0

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build app (inject env variables here)
      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          # 🔒 secrets from GitHub (add them in repo → Settings → Secrets → Actions)
          VITE_PUBLIC_TMDB_API_BASE_URL: ${{ secrets.VITE_PUBLIC_TMDB_API_BASE_URL }}
          VITE_PUBLIC_TMDB_API_KEY: ${{ secrets.VITE_PUBLIC_TMDB_API_KEY }}
          VITE_PUBLIC_TMDB_IMAGE_BASE_URL: ${{ secrets.VITE_PUBLIC_TMDB_IMAGE_BASE_URL }}

      # 5. Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
